# Generated by Django 6.0.2 on 2026-02-28 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("friendly_name", models.CharField(max_length=255)),
                (
                    "domain_name",
                    models.CharField(
                        help_text="SIP domain name for this trunk (e.g. trunk.example.pstn.twilio.com).",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "disaster_recovery_url",
                    models.URLField(
                        blank=True,
                        help_text="Fallback URL for call control when primary URL is unavailable.",
                    ),
                ),
                (
                    "disaster_recovery_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="POST",
                        max_length=6,
                    ),
                ),
                ("recording_enabled", models.BooleanField(default=False)),
                (
                    "secure",
                    models.BooleanField(
                        default=True, help_text="Enforce SRTP/TLS for media and SIP."
                    ),
                ),
                ("cnam_lookup_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
