# Generated by Django 6.0.2 on 2026-02-28 23:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth_tokens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("outbound-call", "Outbound Call"),
                            ("inbound-call", "Inbound Call"),
                            ("recording", "Recording"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "call_sid",
                    models.CharField(blank=True, db_index=True, max_length=36),
                ),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Billed amount in EUR.",
                        max_digits=12,
                    ),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth_tokens.apikey",
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "api_key",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="auth_tokens.apikey",
                    ),
                ),
            ],
        ),
    ]
