# Generated by Django 6.0.2 on 2026-02-28 23:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="E.164 formatted number, e.g. +4930123456789.",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("friendly_name", models.CharField(blank=True, max_length=255)),
                (
                    "iso_country",
                    models.CharField(
                        default="DE", help_text="ISO 3166-1 alpha-2.", max_length=2
                    ),
                ),
                (
                    "number_type",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("mobile", "Mobile"),
                            ("toll-free", "Toll Free"),
                        ],
                        default="local",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("released", "Released"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "voice_url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL called when this number receives an inbound call.",
                    ),
                ),
                (
                    "voice_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="POST",
                        max_length=4,
                    ),
                ),
                (
                    "sipgate_id",
                    models.CharField(
                        blank=True,
                        help_text="Internal Sipgate phoneline/routing ID.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
