# Generated by Django 6.0.2 on 2026-02-28 22:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("ringing", "Ringing"),
                            ("in-progress", "In Progress"),
                            ("completed", "Completed"),
                            ("busy", "Busy"),
                            ("failed", "Failed"),
                            ("no-answer", "No Answer"),
                            ("canceled", "Canceled"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("inbound", "Inbound"),
                            ("outbound-api", "Outbound API"),
                            ("outbound-dial", "Outbound Dial"),
                        ],
                        default="outbound-api",
                        max_length=20,
                    ),
                ),
                ("from_number", models.CharField(max_length=100)),
                ("to_number", models.CharField(max_length=100)),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Webhook URL for call control instructions (TwiML-compatible).",
                    ),
                ),
                (
                    "status_callback",
                    models.URLField(
                        blank=True,
                        help_text="URL to receive call status change notifications.",
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "duration",
                    models.PositiveIntegerField(
                        blank=True, help_text="Duration in seconds.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
