# Generated by Django 6.0.2 on 2026-02-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calls", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="call",
            name="url",
        ),
        migrations.AddField(
            model_name="call",
            name="sipgate_session_id",
            field=models.CharField(
                blank=True,
                help_text="Sipgate session ID for active calls.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="direction",
            field=models.CharField(
                choices=[("inbound", "Inbound"), ("outbound-api", "Outbound API")],
                default="outbound-api",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="from_number",
            field=models.CharField(
                help_text="Caller ID in E.164 format, e.g. +4930123456789.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="status",
            field=models.CharField(
                choices=[
                    ("init", "Init"),
                    ("validate", "Validate"),
                    ("route", "Route"),
                    ("ringing", "Ringing"),
                    ("answered", "Answered"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("denied", "Denied (Fraud / Policy)"),
                    ("canceled", "Canceled"),
                ],
                default="init",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="call",
            name="to_number",
            field=models.CharField(
                help_text="Destination number in E.164 format.", max_length=30
            ),
        ),
    ]
